### ISSUE TITLE
Only need to support Android 4.0+

### ISSUE THREAD

**Issue by trietbui85** [geftimov/android-player#5] opened 2015-05-11 03:29 UTC
According to [Android Platform version](http://developer.android.com/resources/dashboard/platform-versions.html), market share of Android 2.x and 3.x are too small (6%). I think it's safe to set your lib with minSDK=15 now.

**Comment by geftimov** [comment] 2015-05-11 07:16
@anticafe 
Yea, i know.
This was my original intentions.
But i received a issue :
https://github.com/geftimov/android-player/issues/2

**Comment by xiaomeixw** [comment] 2015-05-13 05:12
@anticafe  support for 2.3 or lower , because some app user's phone is very old 。like Facebook ' s app they usually support for more lower version... even there is 6% user( in fact,the most of Africa ‘s android phone is 2.3 or more lower) , but as a android developer we should support for them....
Google‘s Android is not like Apple's IOS...
maybe After one or two years later Argument support for Minimum version is meaningless ， because in that time 2.3 will be less than 1%....but who knows.... so support lower version is good  at present....

@geftimov  I am sorry ，I think the issue is about version Argument, not about project bug...so please close the issue....Thanks...

**Comment by geftimov** [comment] 2015-05-13 05:28
Closing

**Closed as completed by geftimov** 2015-05-13 05:28 UTC
